javascript:(()=>{const TOOL_ID='fbtool-meta-campaign-cleaner';const EXIST=document.getElementById(TOOL_ID);if(EXIST){EXIST.remove();return;}const XLSX_URL='https://cdn.jsdelivr.net/npm/xlsx@0.18.5/dist/xlsx.full.min.js';const style=`
.fbtool{position:fixed;left:50%;top:50%;transform:translate(-50%,-50%);width:min(720px,calc(100vw - 24px));max-height:calc(100vh - 40px);overflow:auto;z-index:2147483647;background:#0f1715;color:#e8fff0;border:1px solid #2b433a;border-radius:14px;box-shadow:0 24px 60px rgba(0,0,0,.45);font:13px/1.4 Inter,"Segoe UI",Arial,sans-serif;padding:14px}.fbtool,*{box-sizing:border-box}.fbtool__header{display:flex;gap:8px;align-items:flex-start;justify-content:space-between;position:relative;padding-right:34px;margin-bottom:10px}.fbtool__title{margin:0;color:#4dff8f;font-size:32px;line-height:1.05;font-weight:800;letter-spacing:.01em}.fbtool__meta{color:#99b3a6;font-size:11px;margin-top:4px}.fbtool__close{position:absolute;top:0;right:0;background:transparent;border:0;color:#d3e8dc;padding:0;cursor:pointer;line-height:1;font-size:24px;font-weight:700}.fbtool__grid{display:grid;grid-template-columns:1fr 1fr;gap:8px}.fbtool label{display:block;margin:8px 0 4px;color:#c7e0d2;font-size:12px;font-weight:500}.fbtool input,.fbtool textarea,.fbtool button{width:100%;border-radius:9px;border:1px solid #2f4a40;background:#121f1b;color:#e8fff0;padding:9px;font:inherit;outline:none}.fbtool textarea{min-height:96px;resize:vertical}.fbtool__btn{cursor:pointer;font-weight:700}.fbtool__btn--primary{background:#4dff8f!important;color:#052012!important;border-color:#4dff8f!important}.fbtool__log{background:#0b1210;border:1px solid #22372f;max-height:180px;overflow:auto;border-radius:10px;padding:9px;white-space:pre-wrap;font:12px/1.45 ui-monospace,SFMono-Regular,Menlo,Monaco,Consolas,"Liberation Mono",monospace}.fbtool__note{margin-top:8px;color:#99b3a6;font-size:11px}.info{color:#c7e0d2}.success{color:#9bff7d}.warning{color:#ffd36b}.error{color:#ff8f8f}@media (max-width:840px){.fbtool__grid{grid-template-columns:1fr}}
`;const root=document.createElement('section');root.id=TOOL_ID;root.className='fbtool';root.innerHTML=`<style>${style}</style><div class="fbtool__header"><div><h1 class="fbtool__title">Campaign Cleaner</h1><div class="fbtool__meta">v 2026.05.13</div></div><button class="fbtool__close" aria-label="Закрыть">×</button></div><label>Загрузи файл экспорта</label><input id="mcc-file" type="file" accept=".csv,.xlsx,.xls"/><label>Параметры замены ID (JSON)</label><textarea id="mcc-repl" placeholder='{"old_pixel_id":"new_pixel_id"}' spellcheck="false"></textarea><div class="fbtool__grid"><div><label>NEW_PIXEL_ID</label><input id="mcc-pixel" type="text"/></div><div><label>NEW_PAGE_ID</label><input id="mcc-page" type="text"/></div><div><label>NEW_IG_ID</label><input id="mcc-ig" type="text"/></div><div><label>Статус после импорта</label><input id="mcc-status" type="text" value="PAUSED"/></div></div><button id="mcc-run" class="fbtool__btn fbtool__btn--primary" style="margin-top:8px">Очистить и скачать</button><label>Лог обработки</label><div id="mcc-log" class="fbtool__log"></div><div class="fbtool__note">Локальная обработка в браузере. Повторный запуск bookmarklet закрывает окно.</div>`;document.body.appendChild(root);root.querySelector('.fbtool__close').onclick=()=>root.remove();
const els={fileInput:root.querySelector('#mcc-file'),replacementsInput:root.querySelector('#mcc-repl'),pixelIdInput:root.querySelector('#mcc-pixel'),pageIdInput:root.querySelector('#mcc-page'),igIdInput:root.querySelector('#mcc-ig'),forceStatusInput:root.querySelector('#mcc-status'),cleanBtn:root.querySelector('#mcc-run'),log:root.querySelector('#mcc-log')};
const jsonLikeColumnPatterns=[/targeting/i,/promoted\s*object/i,/creative/i,/object\s*story\s*spec/i,/asset\s*feed\s*spec/i,/tracking\s*specs/i,/conversion\s*specs/i,/attribution\s*spec/i,/degrees\s*of\s*freedom\s*spec/i,/frequency\s*control\s*specs/i];
const removableJsonKeys=new Set(['id','account_id','campaign_id','adset_id','ad_id','source_campaign_id','source_adset_id','source_ad_id','created_time','updated_time','effective_status','insights']);
const clearExactColumns=new Set(['campaign id','ad set id','adset id','ad id','created time','last updated time','reporting starts','reporting ends']);
const replaceValueColumns={'pixel id':()=>els.pixelIdInput.value.trim(),'facebook page id':()=>els.pageIdInput.value.trim(),'instagram id':()=>els.igIdInput.value.trim()};
const statusColumns=new Set(['campaign status','ad set status','ad status']);
const clearCellPatterns=[/(^|\b)campaign\s*id(\b|$)/i,/(^|\b)ad\s*set\s*id(\b|$)/i,/(^|\b)adset\s*id(\b|$)/i,/(^|\b)ad\s*id(\b|$)/i,/(^|\b)source\s*campaign\s*id(\b|$)/i,/(^|\b)source\s*ad\s*set\s*id(\b|$)/i,/(^|\b)source\s*adset\s*id(\b|$)/i,/(^|\b)source\s*ad\s*id(\b|$)/i];
const dropOnlyColumnPatterns=[/created\s*time/i,/updated\s*time/i,/created\s*at/i,/updated\s*at/i,/delivery/i,/results/i,/reach/i,/impressions/i,/frequency/i,/amount\s*spent/i,/^spend$/i,/cpm/i,/cpc/i,/ctr/i,/clicks/i,/link\s*clicks/i,/purchases/i,/conversions/i,/cost\s*per/i,/budget\s*remaining/i,/quality\s*ranking/i,/engagement\s*rate\s*ranking/i,/conversion\s*rate\s*ranking/i];
const normalizeName=v=>String(v??'').trim().toLowerCase().replace(/[_-]/g,' ');const matchesAnyPattern=(v,p)=>p.some(x=>x.test(normalizeName(v)));const isEmptyCell=v=>v==null||String(v).trim()==='';
const log=(m,t='info')=>{const d=document.createElement('div');d.className=t;d.textContent=`[${new Date().toLocaleTimeString()}] ${m}`;els.log.appendChild(d);els.log.scrollTop=els.log.scrollHeight};
function parseReplacements(){const raw=els.replacementsInput.value.trim();if(!raw)return{};const parsed=JSON.parse(raw);const r={};Object.entries(parsed).forEach(([o,n])=>{if(String(o).trim())r[String(o)]=String(n)});return r}
function tryParseJson(value){if(typeof value!=='string')return{parsed:false,value};const t=value.trim();if(!t)return{parsed:false,value};if(!((t.startsWith('{')&&t.endsWith('}'))||(t.startsWith('[')&&t.endsWith(']'))))return{parsed:false,value};for(const c of [t,...(t.includes("'")&&!t.includes('"')?[t.replaceAll("'",'"')]:[])]){try{return{parsed:true,value:JSON.parse(c)}}catch{}}return{parsed:false,value}}
const replacePlainText=(v,r)=>typeof v!=='string'?v:Object.entries(r).reduce((acc,[o,n])=>acc.split(o).join(n),v);
function deepCleanJson(obj,replacements){if(Array.isArray(obj))return obj.map(x=>deepCleanJson(x,replacements));if(obj&&typeof obj==='object'){const c={};Object.entries(obj).forEach(([k,v])=>{if(removableJsonKeys.has(k))return;if(Object.hasOwn(replacements,k)){c[k]=replacements[k];return;}c[k]=deepCleanJson(v,replacements)});return c}if(typeof obj==='string')return replacements[obj]??obj;return obj}
function cleanCell(value,column,replacements){const parsed=tryParseJson(value);if(parsed.parsed||matchesAnyPattern(column,jsonLikeColumnPatterns)){if(parsed.parsed)return JSON.stringify(deepCleanJson(parsed.value,replacements));return replacePlainText(value,replacements)}return replacePlainText(value,replacements)}
function cleanRows(rows,replacements){if(!rows.length)return{rows,droppedColumns:[]};const original=Object.keys(rows[0]);const dropped=[];let kept=original.filter(c=>{const d=matchesAnyPattern(c,dropOnlyColumnPatterns);if(d)dropped.push(c);return !d});const cleaned=rows.map(row=>{const o={};kept.forEach(c=>{const n=normalizeName(c);if(clearExactColumns.has(n)||matchesAnyPattern(c,clearCellPatterns))o[c]='';else if(statusColumns.has(n))o[c]=els.forceStatusInput.value.trim()||'PAUSED';else if(replaceValueColumns[n])o[c]=replaceValueColumns[n]()||row[c];else o[c]=cleanCell(row[c],c,replacements)});return o});return{rows:cleaned,droppedColumns:dropped}}
function ensureXlsx(){if(window.XLSX)return Promise.resolve();return new Promise((res,rej)=>{const s=document.createElement('script');s.src=XLSX_URL;s.onload=res;s.onerror=()=>rej(new Error('Не удалось загрузить XLSX библиотеку'));document.head.appendChild(s)})}
async function readFileAsArrayBuffer(file){return await file.arrayBuffer()}
function downloadCsvFromFirstSheet(workbook,fileName){const first=workbook.SheetNames[0];const csv=XLSX.utils.sheet_to_csv(workbook.Sheets[first]);const blob=new Blob(['\ufeff'+csv],{type:'text/csv;charset=utf-8'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=fileName;document.body.appendChild(a);a.click();a.remove();URL.revokeObjectURL(url)}
async function processFile(){els.log.innerHTML='';const file=els.fileInput.files?.[0];if(!file){alert('Сначала загрузи CSV/XLSX файл.');return;}els.cleanBtn.disabled=true;els.cleanBtn.textContent='Обрабатываю...';try{await ensureXlsx();const replacements=parseReplacements();log(`Файл: ${file.name}`);const buffer=await readFileAsArrayBuffer(file);const workbook=XLSX.read(buffer,{type:'array',cellDates:false,raw:false});const out=XLSX.utils.book_new();for(const sheetName of workbook.SheetNames){const rows=XLSX.utils.sheet_to_json(workbook.Sheets[sheetName],{defval:'',raw:false});log(`Лист "${sheetName}": строк ${rows.length}`);if(!rows.length){XLSX.utils.book_append_sheet(out,XLSX.utils.aoa_to_sheet([]),sheetName.slice(0,31));continue;}const {rows:cleanedRows,droppedColumns}=cleanRows(rows,replacements);XLSX.utils.book_append_sheet(out,XLSX.utils.json_to_sheet(cleanedRows),sheetName.slice(0,31));if(droppedColumns.length)log(`Удалено колонок: ${droppedColumns.length}`,'success')}const outputName=`${file.name.replace(/\.[^.]+$/,'')}_cleaned.csv`;downloadCsvFromFirstSheet(out,outputName);log(`Готово. Скачан файл: ${outputName}`,'success')}catch(e){log(e.message||String(e),'error');alert(e.message||String(e))}finally{els.cleanBtn.disabled=false;els.cleanBtn.textContent='Очистить и скачать'}}
els.cleanBtn.addEventListener('click',processFile);log('Готов к работе.','success');})();
